version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency-base
    working_dir: /app
    tty: true
    volumes:
      - ./:/app
    ports:
      - "${APP_PORT:-3000}:3000"
      - "${VITE_PORT:-5173}:5173"
    restart: unless-stopped